env:
  browser: true
  es2021: true
  jest/globals: true
extends:
  - airbnb-base
  - prettier
parserOptions:
  ecmaVersion: 12
  sourceType: module
plugins:
  - jest
  - prettier
rules:
  prettier/prettier: ['error']
  no-console: 0
  import/extensions: 0
