env:
  browser: true
  es2021: true
  jest/globals: true
extends:
  - airbnb-base
  - prettier
parser: '@babel/eslint-parser'
parserOptions:
  ecmaVersion: 12
  sourceType: module
plugins:
  - jest
  - prettier
rules:
  no-constructor-return: 0
  prettier/prettier: ['error']
  no-unused-vars: 0
  import/prefer-default-export: 0
  no-console: 0
  arrow-body-style: 0
  import/extensions: 0
  func-names: 0
  no-param-reassign: 0
